# Generated by Django 4.1.3 on 2022-11-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=60)),
                ('registration', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_naMe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CasomiraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of provoz')),
                ('vzlet', models.DateTimeField(verbose_name='vzlet')),
                ('pristani', models.DateTimeField(verbose_name='pristani')),
                ('kapitan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kapitan', to='main.person')),
                ('zak', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='zak', to='main.person')),
            ],
        ),
    ]
