# Generated by Django 4.1.3 on 2022-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_full_name_person_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casomiramodel',
            name='pristani',
            field=models.DateTimeField(default=None, null=True, verbose_name='pristani'),
        ),
        migrations.AlterField(
            model_name='casomiramodel',
            name='vzlet',
            field=models.DateTimeField(default=None, null=True, verbose_name='vzlet'),
        ),
    ]
