# Generated by Django 4.1.3 on 2022-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_casomiramodel_pristani_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of provoz')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='CasomiraModel',
            new_name='Flight',
        ),
    ]
