# Generated by Django 4.1.3 on 2022-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activeperson_rename_casomiramodel_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivePerson',
        ),
    ]
