# Generated by Django 4.1.3 on 2022-11-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_activeperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of provoz')),
                ('aircraft_type', models.CharField(max_length=60)),
                ('registration', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of provoz')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='letadlo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='letadlo', to='main.aircraft'),
        ),
    ]
