# Generated by Django 4.1.3 on 2022-11-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activeaircraft_activeunits_flight_letadlo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveAircraft',
        ),
        migrations.DeleteModel(
            name='ActiveUnits',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='letadlo',
            new_name='aircraft',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='kapitan',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='pristani',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='vzlet',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='zak',
        ),
        migrations.AddField(
            model_name='flight',
            name='captain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='captain', to='main.person'),
        ),
        migrations.AddField(
            model_name='flight',
            name='landing',
            field=models.DateTimeField(default=None, null=True, verbose_name='landing'),
        ),
        migrations.AddField(
            model_name='flight',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student', to='main.person'),
        ),
        migrations.AddField(
            model_name='flight',
            name='takeoff',
            field=models.DateTimeField(default=None, null=True, verbose_name='takeoff'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
