# Generated by Django 4.1.3 on 2022-11-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_aktivni_aircraft_active_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='landing',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='landing'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='student',
            field=models.ForeignKey(default='X', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student', to='main.person'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='takeoff'),
        ),
    ]
