# Generated by Django 4.1.3 on 2022-12-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_flight_landing_alter_flight_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student', to='main.person'),
        ),
    ]
