# Generated by Django 4.1.3 on 2022-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_flight_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date of provoz'),
        ),
    ]
