# Generated by Django 4.1.3 on 2022-12-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_flight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='landing',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='landing'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student', to='main.person'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='takeoff',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='takeoff'),
        ),
    ]
