# Generated by Django 4.1.3 on 2023-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_flight_landing_alter_flight_takeoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraft",
            name="in_the_sky",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="in_the_sky",
            field=models.BooleanField(default=False),
        ),
    ]
